name: loglens
description: A flexible, extensible logging utility with dynamic modules/layers, persistence, and a simple console UI.
version: 0.2.2

homepage: https://github.com/InsNeed/log_lens
repository: https://github.com/InsNeed/log_lens
issue_tracker: https://github.com/InsNeed/log_lens/issues
topics:
  - logging
  - overlay
  - console
  - flutter
  - debugging

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
